AspDotNetProject/Models/DataBaseProvider.cs
namespace AspDotNetProject.Models
{
    public class DataBaseProvider
    {
        public static int DBIndetificator { get; set; } = 0;
    }
}

AspDotNetProject/Models/ErrorViewModel.cs
namespace AspDotNetProject.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

AspDotNetProject/ViewModels/CategoriesListViewModel.cs
using BusinessLogic.Entities;
namespace AspDotNetProject.ViewModels
{
    public class CategoriesListViewModel
    {
        public List<CategoryEntity> Categories { get; set; }
        public CategoryEntity CategoryModel { get; set; }
    }
}

AspDotNetProject/ViewModels/EditTaskViewModel.cs
using BusinessLogic.Entities;
using TaskEntity = BusinessLogic.Entities.TaskEntity;

namespace AspDotNetProject.ViewModels
{
    public class EditTaskViewModel
    {
        public TaskEntity TaskModel { get; set; }
        public List<CategoryEntity> Categories { get; set; }
    }
}

AspDotNetProject/ViewModels/TaskListViewModel.cs
using BusinessLogic.Entities;
using BusinessLogic.intefaces;
using TaskEntity = BusinessLogic.Entities.TaskEntity;

namespace AspDotNetProject.ViewModels
{
    public class TaskListViewModel
    {
        public IEnumerable<TaskEntity> CompleteTasksTable { get; set; }
        public IEnumerable<TaskEntity> UnCompleteTasksTable { get; set; }
        public List<CategoryEntity> Categories { get; set; }
        public TaskEntity TaskModel { get; set; }
        public IRepository Repository { get; set; }
    }
}

AspDotNetProject/Controllers/CategoriesController.cs
using AspDotNetProject.ViewModels;
using Microsoft.AspNetCore.Mvc;
using BusinessLogic.Entities;
using BusinessLogic.intefaces;

namespace AspDotNetProject.Controllers
{
    public class CategoriesController : Controller
    {
        public IRepository repository;

        public CategoriesController(IRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new CategoriesListViewModel
            {
                CategoryModel = new CategoryEntity(),
                Categories = repository.GetAllCategoriesList()
            });
        }
        
        [HttpPost]
        public IActionResult Create(CategoriesListViewModel model)
        {
            repository.CreateCategory(model.CategoryModel);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            return View(repository.GetCategoryById(Id));
        }

        [HttpPost]
        public IActionResult Edit(CategoryEntity category)
        {
            repository.UpdateCategory(category);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int Id)
        {
            repository.DeleteCategory(Id);
            return RedirectToAction("Index");
        }
    }
}

AspDotNetProject/Controllers/ToDoListController.cs
using AspDotNetProject.Enum;
using AspDotNetProject.Models;
using AspDotNetProject.ViewModels;
using BusinessLogic.intefaces;
using Microsoft.AspNetCore.Mvc;


namespace AspDotNetProject.Controllers
{
    public class ToDoListController : Controller
    {
        private readonly IRepository repository;
        public ToDoListController(IRepository repository)
        {
            this.repository = repository;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(new TaskListViewModel
            {
                CompleteTasksTable = Enumerable.Where(repository.GetAllTasksList(), t => t.IsCompleted).OrderBy(t => t.CompletedAt).Reverse(),
                UnCompleteTasksTable = Enumerable.Where(repository.GetAllTasksList(), t => !t.IsCompleted).OrderBy(t => t.DeadLine),
                Categories = repository.GetAllCategoriesList(),
                TaskModel = new BusinessLogic.Entities.TaskEntity(),
                Repository = repository
            });
        }

        [HttpPost]
        public IActionResult Create(TaskListViewModel model)
        {
            if (model.TaskModel.Text != string.Empty)
            {
                repository.CreateTask(model.TaskModel);
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int Id)
        {
            return View(new EditTaskViewModel
            {
                TaskModel = repository.GetTaskById(Id),
                Categories = repository.GetAllCategoriesList()
            });
        }
        
        [HttpPost]
        public IActionResult Edit(EditTaskViewModel model)
        {
            
            var task = model.TaskModel;
            var oldtask = repository.GetTaskById(task.Id);

            task.CreatedAt = oldtask.CreatedAt;
            task.IsCompleted = oldtask.IsCompleted;
            task.CompletedAt = oldtask.CompletedAt;

            repository.UpdateTask(task);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int Id)
        {
            repository.DeleteTask(Id);
            return RedirectToAction("Index");
        }

        public IActionResult Complete(int id)
        {
            var task = repository.GetTaskById(id);
            task.IsCompleted = task.IsCompleted ? false : true;
            task.CompletedAt = DateTime.Now;

            repository.UpdateTask(task);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult DataBaseProvider(string identificator)
        {
            switch (identificator)
            {
                case "mssql":
                    Models.DataBaseProvider.DBIndetificator = (int)DataBaseEnum.MSSQL;
                    break;
                case "xml":
                    Models.DataBaseProvider.DBIndetificator = (int)DataBaseEnum.XML;
                    break;

                default:
                    break;
            }
            return RedirectToAction("Index");
        }
    }
}

AspDotNetProject/Views/Categories/Edit.cshtml
@model BusinessLogic.Entities.CategoryEntity

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group p-2">
                <label asp-for="Text" class="control-label"></label>
                <input asp-for="Text" class="form-control" />
                <span asp-validation-for="Text" class="text-danger"></span>
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspDotNetProject/Views/Categories/Index.cshtml
@model AspDotNetProject.ViewModels.CategoriesListViewModel;

@{
    ViewData["Title"] = "Index";
}

<div class="p-2 text-center">
    <label>New category</label>
    <form asp-action="Create" asp-controller="Categories" method="post">
        <input class="form-control btn-group w-25" asp-for="CategoryModel.Text" placeholder="Text" type='text' maxlength=50 required  />
        <input class="btn btn-primary" type="submit"/>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CategoryModel.Text)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Categories) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Text)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |    
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

AspDotNetProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspDotNetProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspDotNetProject.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspDotNetProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ToDoList" asp-action="Index">My tasks</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>
                    </ul>
                    <form asp-action="DataBaseProvider" method="get">
                        <select name="identificator" onchange="this.form.submit();" class="form-control">
                            <option>Change database:</option>
                            <option value="xml">XML</option>
                            <option value="mssql">MSSQL</option>
                        </select>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - AspDotNetProject - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AspDotNetProject/Views/ToDoList/Edit.cshtml
@model AspDotNetProject.ViewModels.EditTaskViewModel;

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Task</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TaskModel.Id" /> 
            <div class="form-group p-2">
                <label asp-for="TaskModel.CategoryId" class="control-label">Category</label>
                <select asp-for="TaskModel.CategoryId" class="form-control">
                    @foreach(var item in Model.Categories){
                        <option value="@item.Id">@item.Text</option>
                    }
                </select>
                <span asp-validation-for="TaskModel.CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group p-2">
                <label asp-for="TaskModel.Text" class="control-label"></label>
                <input asp-for="TaskModel.Text" class="form-control" />
                <span asp-validation-for="TaskModel.Text" class="text-danger"></span>
            </div>
            <div class="form-group p-2">
                <label asp-for="TaskModel.DeadLine" class="control-label"></label>
                <input asp-for="TaskModel.DeadLine" class="form-control" />
                <span asp-validation-for="TaskModel.DeadLine" class="text-danger"></span>
            </div>
            <div class="form-group p-2">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

AspDotNetProject/Views/ToDoList/Index.cshtml
@model AspDotNetProject.ViewModels.TaskListViewModel;

@{
    ViewData["Title"] = "Index";
}
<style>
    input{

    }
</style>
<script>
    window.addEventListener("click", function(ev){
        let target = ev.target;
        if(target.tagName == "INPUT"){
             if(target.parentNode.tagName == "TD"){
                 if(target.getAttribute("checked")){
                     location.href = "./ToDoList/Complete?Id=" + target.parentNode.lastChild.value;
                     return 0;
                 }
             }
        }
        if(target.tagName == "INPUT"){
            if(target.parentNode.tagName == "TD"){
                location.href = "./ToDoList/Complete?Id=" + target.parentNode.lastChild.value;
            }
        }
    });
</script>
<div class="p-2 text-center">
    <label>New task</label>
    <form asp-action="Create" asp-controller="ToDoList" method="post">
        <input class="form-control btn-group w-25" asp-for="TaskModel.Text" placeholder="Text" type='text' maxlength=50 required  />
        <input class="form-control btn-group w-25 " asp-for="TaskModel.DeadLine" type="datetime-local">
        <select class="form-control btn-group w-25" asp-for="TaskModel.CategoryId">
            @foreach (var item in Model.Categories)
            {
                <option value="@item.Id">@item.Text</option>
            }
        </select>

        <input class="btn btn-primary" type="submit"/>
    </form>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayName("Complete")
            </th>
            <th>
                @Html.DisplayName("Text")
            </th>
            <th>
                @Html.DisplayName("DeadLine")
            </th>
            <th>
                @Html.DisplayName("Category")
            </th>
            <th>
                @Html.DisplayName("CreateAt")
            </th>
            <th>Controls</th>
        </tr>
    </thead>
    <tbody>
        @if(Model.UnCompleteTasksTable.Count() > 0){
        @foreach (var item in Model.UnCompleteTasksTable) {
            <tr @if(item.DeadLine <= DateTime.Now){@("style=background:rgba(256,0,0,0.2);")}>
                <td><input type="checkbox" /><input type="hidden" value="@item.Id"/></td>
                <td>@item.Text</td>
                <td>@if (item.DeadLine <= DateTime.Now)
                    {
                        <del>@item.DeadLine</del>
                    }else{
                        @item.DeadLine
                    }
                </td>
                <td>
                    @Model.Repository.GetCategoryById(item.CategoryId).Text
                </td>
                <td>@item.CreatedAt</td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { item.Id }) 
                </td>
                </tr>
            }

        }
        else
        {
            <tr>
                <td colspan=6>There is nothing to show..</td>
            </tr>
        }
    </tbody>
</table>

<table class="table my-2">
        <thead>
        <tr>
            <th>UnComplete</th>
            <th>Text</th>
            <th>DeadLine</th>
            <th>Category</th>
            <th>CompletedAt</th>
            <th></th>
        </tr>
    </thead>
        <tbody>
        @if (Model.CompleteTasksTable.Count() > 0)
        {
            @foreach (var item in Model.CompleteTasksTable)
            {
                <tr @if(item.DeadLine <= DateTime.Now){@("style=background:rgba(256,0,0,0.2);")}>
                    <td><input checked type="checkbox" /><input type="hidden" value="@item.Id"/></td>
                    <td>@item.Text</td>
                    <td>@item.DeadLine</td>
                    <td>
                        @Model.Repository.GetCategoryById(item.CategoryId).Text
                    </td>
                    <td>@item.CompletedAt</td>
                    <td>
                        @Html.ActionLink("Edit", "Edit", new { item.Id }) |
                        @Html.ActionLink("Delete", "Delete", new { item.Id })
                    </td>
                </tr>
            }
         }else{
                <tr>
                    <td colspan=6>There is nothing to show..</td>
                </tr>
            }
            </tbody>
</table>